export const userSelector = _ => _.user.data
export const userPublicSelector = _ => _.user.current
export const authSelector = _ => _.auth
export const listsSelector = _ => _.lists.data
export const listSelector = _ => _.lists.currentList
export const productSelector = _ => _.product.current
export const productTempSelector = _ => _.product.data
export const filesSelector = _ => _.files
export const friendsSelector = _ => _.friends.data